server:
  port: 8888

endpoints.sensitive: false

spring:
  datasource:
    url: jdbc:h2:mem:TEST;MVCC=true;DB_CLOSE_DELAY=-1;MODE=Mysql
#    url: jdbc:h2:file:./eventstore;MODE=Oracle;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    validation-query: SELECT 1;

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

  h2:
    console:
      enabled: true
      path: /h2-console